# Generated by Django 3.2.25 on 2024-09-12 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Товар')),
                ('info', models.TextField(verbose_name='Описание')),
                ('base_cost', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Базовая цена')),
                ('sort_order', models.CharField(choices=[('ASC', 'Asc'), ('DESC', 'Desc')], default='ASC', max_length=4)),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='Parameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=80, verbose_name='Имя параметра')),
                ('value', models.CharField(blank=True, max_length=80, verbose_name='Значение параметра')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Цена')),
                ('sort_order', models.CharField(choices=[('ASC', 'Asc'), ('DESC', 'Desc')], default='ASC', max_length=4)),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='catalog.goods')),
            ],
            options={
                'verbose_name': 'Параметр',
                'verbose_name_plural': 'Параметры',
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('sign', models.CharField(max_length=55, verbose_name='Подпись')),
                ('sort_order', models.CharField(choices=[('ASC', 'Asc'), ('DESC', 'Desc')], default='ASC', max_length=4)),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.goods')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
            },
        ),
    ]
